version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend-composecontainer
    ports:
      - "8001:80"
    volumes:
      - frontend-build:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - mern


  backend:
    build: ./backend      # take from my dockerfile
    container_name: backend-composecontainer
    ports:
      - "5001:5050"
    volumes:
      - backend-code:/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/BugTrack
      - MINIO_ENDPOINT=http://minio:9000
    depends_on:
      - mongodb
      - minio
    networks:
      - mern

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mern

 # Minio docker container is not working
  # minio:
  #   image: minio/minio
  #   command: server /data --console-address ":9001"
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - minio-data:/data/miniodb
  #   environment:
  #     - MINIO_ROOT_USER=minioadmin
  #     - MINIO_ROOT_PASSWORD=minioadmin
  #   networks:
  #     - mern


volumes:
  mongodb-data:
  minio-data:
  backend-code:
  frontend-build:

networks:
  mern:
    driver: bridge
